#!/usr/bin/env bash
# Denies all incoming traffic apart from SSH, HTTPS and HTTP
#Install ufw firewall on web-01 by running the following command
sudo apt-get install ufw
#Enable ufw after installing 
sudo ufw enable
#Set the default incoming policy to deny all traffic
sudo ufw default deny incoming
#Set the default outgoing policy to allow all traffic
sudo ufw default allow outgoing
sudo ufw allow ssh
#Allow incoming traffic on port 22 (SSH)
sudo ufw allow 22/tcp
#Allow incoming traffic on port 443 (HTTPS SSL)
sudo ufw allow 443/tcp
#Allow incoming traffic on port 80 (HTTP):
sudo ufw allow 80/tcp
sudo ufw allow https
sudo ufw allow http
#check the status of ufw to confirm that the rules have been applied correctly:
sudo ufw enable
